version: "3.9"
services:
  app-php:
    image: ghcr.io/magic0212/my-laravel/app-php:latest
    env_file:
      - /opt/my-laravel/.env.production
    volumes:
      - /opt/my-laravel/storage/logs:/var/www/html/storage/logs
      - /opt/my-laravel/storage/app:/var/www/html/storage/app
    networks: [prodnet]

  app-nginx:
    image: ghcr.io/magic0212/my-laravel/app-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on: [app-php]
    networks: [prodnet]

networks:
  prodnet: