version: "3.9"
services:
  app-php:
    image: ghcr.io/magic0212/my-laravel/app-php:latest
    env_file:
      - /opt/my-laravel/.env.production
    volumes:
      - /opt/my-laravel/storage:/var/www/html/storage
      - /opt/my-laravel/bootstrap/cache:/var/www/html/bootstrap/cache
    networks: [prodnet]

  app-nginx:
    image: ghcr.io/magic0212/my-laravel/app-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on: [app-php]
    volumes:
      - /opt/my-laravel/app:/var/www/html  # Mount toàn bộ source code
    networks: [prodnet]

networks:
  prodnet: