name: Release & Deploy (tag)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Lấy tên tag (vd: v1.0.3)
      - name: Extract tag
        id: vars
        run: echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      # Ép lowercase owner/repo và tạo đường dẫn image GHCR (tất cả lowercase)
      - name: Prepare lowercase image names
        run: |
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          OWNER_LC="$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')"
          REPO_LC="$(echo "$REPO"   | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE_PHP=ghcr.io/${OWNER_LC}/${REPO_LC}/app-php" >> $GITHUB_ENV
          echo "IMAGE_NGINX=ghcr.io/${OWNER_LC}/${REPO_LC}/app-nginx" >> $GITHUB_ENV

          # Kiểm tra không còn chữ hoa
          echo "PHP image: $IMAGE_PHP"
          echo "NGX image: $IMAGE_NGINX"
          if echo "$IMAGE_PHP$IMAGE_NGINX" | grep -q '[A-Z]'; then
            echo "Image path still has uppercase!"; exit 1; fi

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push PHP-FPM
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/php-fpm/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PHP }}:${{ steps.vars.outputs.TAG }}

      - name: Build & Push Nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/nginx/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NGINX }}:${{ steps.vars.outputs.TAG }}
