name: Release & Deploy (tag)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Lấy tên tag
      - name: Extract tag
        id: vars
        run: echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      # Ép lowercase owner/repo
      - name: Prepare lowercase image names
        run: |
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          OWNER_LC="$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')"
          REPO_LC="$(echo "$REPO"   | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE_PHP=ghcr.io/${OWNER_LC}/${REPO_LC}/app-php" >> $GITHUB_ENV
          echo "IMAGE_NGINX=ghcr.io/${OWNER_LC}/${REPO_LC}/app-nginx" >> $GITHUB_ENV

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push PHP-FPM
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/php-fpm/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PHP }}:${{ steps.vars.outputs.TAG }}

      - name: Build & Push Nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/nginx/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NGINX }}:${{ steps.vars.outputs.TAG }}

      # Copy source code to server
      - name: Copy source code to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT || 22 }}
          source: "app/"
          target: "/opt/my-laravel/"
          timeout: 60s
          command_timeout: 30m

      # Copy .env.production to server
      - name: Copy .env.production to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT || 22 }}
          source: ".env.production"
          target: "/opt/my-laravel/"
          timeout: 60s
          command_timeout: 30m

      # Copy docker-compose file to server
      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT || 22 }}
          source: "docker-compose.prod.yml"
          target: "/opt/my-laravel/"
          timeout: 60s
          command_timeout: 30m

      # Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT || 22 }}
          timeout: 60s
          command_timeout: 30m
          script: |
            # Tạo thư mục cần thiết
            sudo mkdir -p /opt/my-laravel/storage
            sudo mkdir -p /opt/my-laravel/bootstrap/cache
            
            # Cấp quyền cho thư mục
            sudo chown -R 1000:1000 /opt/my-laravel/storage
            sudo chown -R 1000:1000 /opt/my-laravel/bootstrap/cache
            sudo chmod -R 775 /opt/my-laravel/storage
            sudo chmod -R 775 /opt/my-laravel/bootstrap/cache
            
            # Login to GHCR
            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Pull latest images
            sudo docker pull ${{ env.IMAGE_PHP }}:${{ steps.vars.outputs.TAG }}
            sudo docker pull ${{ env.IMAGE_NGINX }}:${{ steps.vars.outputs.TAG }}
            
            # Stop existing containers
            sudo docker-compose -f /opt/my-laravel/docker-compose.prod.yml down || true
            
            # Update docker-compose.prod.yml with new image tags
            sudo sed -i "s|ghcr.io/.*/app-php:.*|${{ env.IMAGE_PHP }}:${{ steps.vars.outputs.TAG }}|g" /opt/my-laravel/docker-compose.prod.yml
            sudo sed -i "s|ghcr.io/.*/app-nginx:.*|${{ env.IMAGE_NGINX }}:${{ steps.vars.outputs.TAG }}|g" /opt/my-laravel/docker-compose.prod.yml
            
            # Start new containers
            sudo docker-compose -f /opt/my-laravel/docker-compose.prod.yml up -d
            
            # Kiểm tra containers đang chạy
            echo "=== Running containers ==="
            sudo docker ps
            
            # Clean up old images
            sudo docker image prune -f